input_dir: ../../../
output_dir: ../
strings:
  inputs: Misc/Translations/en.lproj/
  filter: .+\.strings$
  outputs:
    - templateName: structured-swift5
      output: Translations.swift
xcassets:
  inputs:
    - Misc/Assets.xcassets
  outputs:
    - templateName: swift5
      output: Assets.swift
